$(document).ready(
  $("#div1").click(function(){
    $(this).toggle(1000);
  });
  $("#webtitle").mouseenter(function(){
    $(this).fadeTo('fast',0.05);
    $("#div1").fadeOut(1000);
    $("#div2").fadeOut(1000);  
  });
  $("#webtitle").mouseleave(function(){
    $(this).fadeTo('fast',1);
    $("#div1").fadeIn(1000);
    $("#div2").fadeIn(1000);
  });
);
